TY_RMS_Multiple_Manage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'multiple'

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^main/', views.main, name='main'),
    url(r'^user/', include('user.urls')),
    url(r'^drug/', include('drug.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^warning/', include('warning.urls')),
    url(r'^humiture/', include('humiture.urls')),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^dataReport/', include('dataReport.urls')),
    url(r'^drugTemplate/', include('drugTemplate.urls')),
    url(r'^stockTaking/', include('stockTaking.urls')),
    url(r'^version/', include('version.urls')),
    url(r'^approve/', include('approve.urls')),
    url(r'^standard/', include('standard.urls')),

    # 危化品
    url(r'^Hazardous/', include('Hazardous.urls')),

    url(r'^keyCabinet/', include('keyCabinet.urls')),

    # 登录
    url(r'^account/login/$', views.account_login, name='account_login'),
    url(r'^account/barcode/$', views.account_barcode, name='account_barcode'),
    # 退出系统
    url(r'^account/logout/$', views.account_logout, name='account_logout'),
    # 试剂扫码查询
    url(r'^drug/scanBarCode/$', views.drug_scanBarCode, name='drug_scanBarCode'),
    # 试剂列表首页
    url(r'^drug/index/$', views.drug_index, name='drug_index'),
    # 编辑试剂表单页面
    url(r'^drug/form/$', views.drug_form, name='drug_form'),
    # 试剂表单页面
    url(r'^drug/drugTypeForm/$', views.drug_drugTypeForm, name='drug_drugTypeForm'),
    # 获取试剂类型列表json处理url
    url(r'^drug/GetDrugListJson/$', views.drug_GetDrugListJson, name='drug_GetDrugListJson'),
    # 获取试剂类型的JSON数据
    url(r'^drug/GetDrugTypeListJson/$', views.drug_GetDrugTypeListJson, name='drug_GetDrugTypeListJson'),
    # 试剂模板页面首页
    url(r'^drugTemplate/index/$', views.drugTemplate_index, name='drugTemplate_index'),
    # 新增试剂模板
    url(r'^drugTemplate/form/$', views.drugTemplate_form, name='drugTemplate_form'),
    # 修改试剂
    url(r'^drugTemplate/(?P<template_id>.*)/update_form/$', views.drugTemplate_update_form, name='drugTemplate_update_form'),
    # 新增单次模板条目
    url(r'^drugTemplate/itemForm/$', views.drugTemplate_itemForm, name='drugTemplate_itemForm'),
    # 新增模板视图路由
    url(r'^drugTemplate/SaveTemplateData/$', views.drugTemplate_saveTemplateData, name='drugTemplate_saveTemplateData'),
    # 获取访问入库模板JSON数据
    url(r'^drugTemplate/getTemplateListJson/$', views.drugTemplate_getTemplateListJson, name='drugTemplate_getTemplateListJson'),
    # 获取ClientId Json数据
    url(r'^drugTemplate/ClientListJson/$', views.drugTemplate_clientListJson, name='drugTemplate_clientListJson'),
    # 删除模板
    url(r'^drugTemplate/deleteTemplate/$', views.drugTemplate_deleteTemplate, name='drugTemplate_deleteTemplate'),
    # 日志列表首页
    url(r'^log/index/$', views.log_index, name='log_index'),
    #mxh_试剂详细信息统计
    url(r'dataReport/drug_GetDrugListJson/$',views.drug_GetDrugListJson,name='drug_GetDrugListJson'),
    # 首页试剂记录页面
    url(r'^home/(?P<drug_id>.*)/homeDrugRecord/$', views.home_homeDrugRecord, name='home_homeDrugRecord'),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'TY_RMS_Multiple_Manage.views.page_not_found'

api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [

    # 获取试剂Json数据
    url(r'^getDrugList/$', views.getDrugList, name='getDrugList'),

    # 获取用户列表
    url(r'^getUserList/$', views.getUserList, name='getUserList'),
    url(r'^form_total/', views.form_total, name='form_total'),
    url(r'^usage_record/', views.usage_record, name='usage_record'),
    # 获取用户流转记录
    url(r'^getDrugRecordList/$', views.getDrugRecordList, name='getDrugRecordList'),
    # 申购提醒
    url(r'^getWantPurchaseList/$', views.getWantPurchaseList,
        name='getWantPurchaseList'),
    # 待入库提醒
    url(r'^getAcceptance/$', views.getAcceptance, name='getAcceptance'),
    # 报表数据统计数（今日入库，今日领用， 今日归还， 采购到货）
    url(r'^getStatisticalData/$', views.getStatisticalData, name='getStatisticalData'),
    # 库存量
    url(r'^getAllStockCount/$', views.getAllStockCount, name='getAllStockCount'),
    # 常用试剂
    url(r'^getOftenUse/$', views.getOftenUse, name='getOftenUse'),
    # 大屏页面
    url(r'^index/$', views.index, name='index'),
    # 获取预警Json数据
    url(r'getWarningListJson/', views.getWarningListJson, name='getWarningListJson'),
    # 获取温度echarts展示数据
    url(r'^getTemperatureEchartsJson/.*$', views.getTemperatureEchartsJson, name='getTemperatureEchartsJson'),

]

version/urls.py
from django.conf.urls import url

from . import views

app_name = 'version'

urlpatterns = [

    url(r'index/$', views.index, name='index'),
    # 获取所有的版本信息
    url(r'get_version_list_json/$', views.get_version_list_json, name='get_version_list_json'),
    # 新增版本信息
    url(r'add_version/.*?$', views.add_version, name='add_version'),
    # 保存新增或修改版本信息
    url(r'save_version/$', views.save_version, name='save_version'),
    # 删除版本信息
    url(r'delete_version/$', views.delete_version, name='delete_version'),

]

version/models.py
from django.db import models

# Create your models here.

version/views.py
import json
from datetime import datetime

from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from Business.BllClientVeision import BllClientVersion
from Lib.Utils import Utils
from DataEntity.EntityClientVersion import EntityClientVersion


# 获取版本管理首页
def index(request):
    search_word = request.GET.get('searchValue')
    return render(request, 'version/index.html', locals())


# 获取终端版本信息
def get_version_list_json(request):
    if request.method == 'GET':
        search_word = request.GET.get('searchValue')
        # 如果有值则代表搜索
        version_list = BllClientVersion().get_search_list(search_word)
        version_list = Utils.resultAlchemyData(version_list)
        return JsonResponse({'data': json.loads(version_list)})


# 新增版本信息
def add_version(request):
    if request.method == 'GET':
        version_id = request.GET.get('version_id')
        if not version_id:
            return render(request, 'version/add_version.html', locals())
        version_obj = BllClientVersion().findEntity(version_id)
        return render(request, 'version/add_version.html', locals())


# 保存版本信息
def save_version(request):
    version_id = request.POST.get('VersionId')
    version_code = request.POST.get('VersionCode')
    version_name = request.POST.get('VersionName')
    down_link = request.POST.get('DownLink')
    version_info = request.POST.get('VersionInfo')
    version_code_obj = BllClientVersion().findEntity(EntityClientVersion.VersionCode == version_code)
    if not version_id:
        # 获取当前登录用户
        if version_code_obj:
            return JsonResponse(Utils.resultData(0, '该版本号已存在，请重新输入!'))
        user = request.session['login_user']
        version_obj = EntityClientVersion(VersionId=str(Utils.UUID()), VersionName=version_name,
                                          VersionCode=version_code, DownLink=down_link, VersionInfo=version_info,
                                          CreateDate=datetime.now(), CreateUserId=user['UserId'],
                                          CreateUserName=user['RealName'], IsAdd=1)
        bool_ = BllClientVersion().insert(version_obj)
        if bool_:
            return JsonResponse(Utils.resultData(1, '新增成功！'))
        else:
            return JsonResponse(Utils.resultData(0, '新增失败, 数据异常！'))

    version_obj = BllClientVersion().findEntity(version_id)
    if not version_code_obj or version_code_obj.VersionCode == version_obj.VersionCode:
        version_obj.VersionCode = version_code
        version_obj.VersionName = version_name
        version_obj.DownLink = down_link
        version_obj.VersionInfo = version_info
        bool_ = BllClientVersion().update(version_obj)
        if bool_:
            return JsonResponse(Utils.resultData(1, '修改成功！'))
        else:
            return JsonResponse(Utils.resultData(0, '新增失败, 数据异常！'))
    else:
        return JsonResponse(Utils.resultData(0, '该版本号已存在，请重新输入!'))


# 删除指定的版本
@csrf_exempt
def delete_version(request):
    version_id = request.POST.get('VersionId')
    if version_id:
        BllClientVersion().delete(EntityClientVersion.VersionId==version_id)
        return JsonResponse(Utils.resultData(1, '删除成功'))
    else:
        return JsonResponse(Utils.resultData(0, '删除失败'))

templates/version/add_version.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
    body {
        background-color: #FFF !important;
    }

    .myForm {
        padding-top: 30px;
        padding-right: 50px;
    }
</style>

<div class="ibox float-e-margins">
    <form class="form-horizontal myForm" role="form">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-sm-2 control-label" for="ds_host">版本号*</label>
            <div class="col-sm-4">
                <input class="form-control" type="hidden" id="VersionId" name="VersionId" value="{% firstof version_obj.VersionId '' %}"/>
                <input class="form-control" id="VersionCode" maxlength="50" required="required" name="VersionCode" type="text" value="{% firstof version_obj.VersionCode '' %}" />
            </div>
            <label class="col-sm-2 control-label" for="ds_name">版本名称*</label>
            <div class="col-sm-4">
                <input class="form-control" id="VersionName" maxlength="50" required="required" name="VersionName" type="text" value="{% firstof version_obj.VersionName '' %}" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="ds_username">下载链接*</label>
            <div class="col-sm-10">
                <input class="form-control" id="DownLink" name="DownLink" maxlength="50" required="required" type="text" value="{% firstof version_obj.DownLink '' %}" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="ds_username">版本信息</label>
            <div class="col-sm-10">
                <textarea id="VersionInfo" name="VersionInfo" class="form-control" maxlength="50" style="height:250px"  aria-required="true">{% firstof version_obj.VersionInfo '' %}</textarea>
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <div class="col-sm-12 col-sm-offset-2">
                <button class="btn btn-primary" type="submit">保存内容</button>&nbsp;&nbsp;&nbsp;
                <button class="btn btn-white" type="button" id="closeForm">关闭</button>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    var index = parent.layer.getFrameIndex(window.name);
    $(function () {
        $("#IsSuperviseSwich").change(function () {

            $("#IsSupervise").val($("#IsSuperviseSwich").is(":checked") ? 1 : 0);
        })
        $(".myForm").submit(function () {
            var loadIndex = layer.load(2);
            $.post('{% url 'version:save_version' %}', $(this).serialize(), function (obj) {
                layer.close(loadIndex);
                if (obj.status == 1) {
                    msg("保存成功", function () {
                        parent.layer.close(index);
                    });
                }
                else {
                    msg(obj.message);
                }
            });
            return false;
        })
        $("#closeForm").click(function () {
            parent.layer.close(index);
        });
    })
</script>


{% endblock %}

templates/version/index.html
{% extends 'base.html' %}
{% block content %}
<div class="wrapper wrapper-content animated fadeInDown">
    <div class="mail-box-header">
        <form method="get" action="{% url 'version:index' %}" class="pull-right mail-search" accept-charset="UTF-8">
            <div class="input-group">
                <input type="text" class="form-control input-sm" id="search_word" name="searchValue" placeholder="版本名称、版本号" value="{% firstof search_word '' %}">
                <div class="input-group-btn">
                    <button type="submit" id="btnTableSearch" class="btn btn-sm btn-primary">
                        搜索
                    </button>
                </div>
            </div>
        </form>
        <div class="mail-tools tooltip-demo">
            <button class="btn btn-white btn-sm" data-toggle="tooltip" id="btnTableReload" data-placement="left" title="刷新版本列表"><i class="fa fa-refresh"></i> 刷新</button>
            <button class="btn btn-white btn-sm" data-toggle="tooltip" id="btnTableAdd" data-placement="top" title="添加新版本">
                <i class="fa fa-plus-square"> 新增版本</i>
            </button>
            <button class="btn btn-white btn-sm" data-toggle="tooltip" id="btnTableEdit" data-placement="top" title="编辑选中版本">
                <i class="fa fa-edit"> 编辑版本</i>
            </button>
            <button class="btn btn-white btn-sm" data-toggle="tooltip" id="btnTableDelete" data-placement="top" title="删除选中版本">
                <i class="fa fa-trash-o"> 删除</i>
            </button>
        </div>
    </div>
    <div class="ibox-content">
        <table id="dataTableModel" class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
                <tr>
                    <th>版本Id</th>
                    <th>版本号</th>
                    <th>版本名称</th>
                    <th>下载链接</th>
                    <th>创建世间</th>
                    <th>创建人</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
            <tfoot>
                <tr>
                    <th>版本Id</th>
                    <th>版本号</th>
                    <th>版本名称</th>
                    <th>下载链接</th>
                    <th>创建时间</th>
                    <th>创建人</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
<script type="text/javascript">

    $(function () {
        $('#navTitle', window.parent.document).text('版本管理');
        var searchValue = $('#search_word').val();
        $("#searchValue").val(searchValue);
        var tableModel = $('#dataTableModel').DataTable({
            searching: false,
            lengthChange: false,
            select: true,
            ajax: {
                url: '{% url 'version:get_version_list_json' %}',
                data: { searchValue: searchValue },
                dataSrc: 'data'
            },
            columns: [
            { data: 'VersionId' },
            { data: 'VersionCode' },
            { data: 'VersionName' },
            { data: 'DownLink' },
            { data: 'CreateDate' },
            { data: 'CreateUserName' }
            ],
            createdRow: function (row, data, dataIndex) {
                $(row).children('td').eq(3).html(format_sqlAlchemy_date(data.CreateDate))
            },
            columnDefs: [
    {
        "targets": [0],
        "visible": false
    }
            ],
            "order": [[4, "desc"]]
        });

        $("#btnTableReload").click(function () {
            location.href = '{% url 'version:index' %}';
        });
        $("#btnTableAdd").click(function () {

            parent.layer.open({
                title: "新增版本",
                shift: 2,
                type: 2,
                area: ['860px', '520px'],
                //
                content: ['{% url 'version:add_version' %}', 'no'],
                end: function () {
                    tableModel.ajax.reload();
                }
            });
        });
        $("#btnTableEdit").click(function () {
            var selectRow = tableModel.row('.selected').data();
            if (selectRow == null) {
                layer.msg("请选择要编辑的数据！");
                return;
            }
            parent.layer.open({
                title:"编辑版本信息",
                shift: 2,
                type: 2,
                area: ['860px', '520px'],
                //
                content: ['/version/add_version/?version_id=' + selectRow.VersionId, 'no'],
                end: function () {
                    tableModel.ajax.reload();
                }
            });
        });

        $("#btnTableDelete").click(function () {
            var selectRow = tableModel.row('.selected').data();
            if (selectRow == null) {
                layer.msg("请选择要删除的数据！");
                return;
            }
            parent.layer.confirm('确定要删除此版本', function (index) {
                parent.layer.close(index);
                $.post('{% url 'version:delete_version' %}', { VersionId: selectRow.VersionId }, function (obj) {

                    if (obj.status == 1) {
                        layer.msg("删除成功！");
                        tableModel.row('.selected').remove().draw(false);
                    }
                    else {
                        layer.msg("删除失败！");
                    }
                })
            });
        });

        $("#tablePre").click(function () {
            $("#dataTableModel_previous").click();

        })

        $("#tableNext").click(function () {
            $("#dataTableModel_next").click();

        })
    });
</script>
{% endblock %}