TY_RMS_Multiple_Manage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'multiple'

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^main/', views.main, name='main'),
    url(r'^user/', include('user.urls')),
    url(r'^drug/', include('drug.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^warning/', include('warning.urls')),
    url(r'^humiture/', include('humiture.urls')),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^dataReport/', include('dataReport.urls')),
    url(r'^drugTemplate/', include('drugTemplate.urls')),
    url(r'^stockTaking/', include('stockTaking.urls')),
    url(r'^version/', include('version.urls')),
    url(r'^approve/', include('approve.urls')),
    url(r'^standard/', include('standard.urls')),

    # 危化品
    url(r'^Hazardous/', include('Hazardous.urls')),

    url(r'^keyCabinet/', include('keyCabinet.urls')),

    # 登录
    url(r'^account/login/$', views.account_login, name='account_login'),
    url(r'^account/barcode/$', views.account_barcode, name='account_barcode'),
    # 退出系统
    url(r'^account/logout/$', views.account_logout, name='account_logout'),
    # 试剂扫码查询
    url(r'^drug/scanBarCode/$', views.drug_scanBarCode, name='drug_scanBarCode'),
    # 试剂列表首页
    url(r'^drug/index/$', views.drug_index, name='drug_index'),
    # 编辑试剂表单页面
    url(r'^drug/form/$', views.drug_form, name='drug_form'),
    # 试剂表单页面
    url(r'^drug/drugTypeForm/$', views.drug_drugTypeForm, name='drug_drugTypeForm'),
    # 获取试剂类型列表json处理url
    url(r'^drug/GetDrugListJson/$', views.drug_GetDrugListJson, name='drug_GetDrugListJson'),
    # 获取试剂类型的JSON数据
    url(r'^drug/GetDrugTypeListJson/$', views.drug_GetDrugTypeListJson, name='drug_GetDrugTypeListJson'),
    # 试剂模板页面首页
    url(r'^drugTemplate/index/$', views.drugTemplate_index, name='drugTemplate_index'),
    # 新增试剂模板
    url(r'^drugTemplate/form/$', views.drugTemplate_form, name='drugTemplate_form'),
    # 修改试剂
    url(r'^drugTemplate/(?P<template_id>.*)/update_form/$', views.drugTemplate_update_form, name='drugTemplate_update_form'),
    # 新增单次模板条目
    url(r'^drugTemplate/itemForm/$', views.drugTemplate_itemForm, name='drugTemplate_itemForm'),
    # 新增模板视图路由
    url(r'^drugTemplate/SaveTemplateData/$', views.drugTemplate_saveTemplateData, name='drugTemplate_saveTemplateData'),
    # 获取访问入库模板JSON数据
    url(r'^drugTemplate/getTemplateListJson/$', views.drugTemplate_getTemplateListJson, name='drugTemplate_getTemplateListJson'),
    # 获取ClientId Json数据
    url(r'^drugTemplate/ClientListJson/$', views.drugTemplate_clientListJson, name='drugTemplate_clientListJson'),
    # 删除模板
    url(r'^drugTemplate/deleteTemplate/$', views.drugTemplate_deleteTemplate, name='drugTemplate_deleteTemplate'),
    # 日志列表首页
    url(r'^log/index/$', views.log_index, name='log_index'),
    #mxh_试剂详细信息统计
    url(r'dataReport/drug_GetDrugListJson/$',views.drug_GetDrugListJson,name='drug_GetDrugListJson'),
    # 首页试剂记录页面
    url(r'^home/(?P<drug_id>.*)/homeDrugRecord/$', views.home_homeDrugRecord, name='home_homeDrugRecord'),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'TY_RMS_Multiple_Manage.views.page_not_found'

api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [

    # 获取试剂Json数据
    url(r'^getDrugList/$', views.getDrugList, name='getDrugList'),

    # 获取用户列表
    url(r'^getUserList/$', views.getUserList, name='getUserList'),
    url(r'^form_total/', views.form_total, name='form_total'),
    url(r'^usage_record/', views.usage_record, name='usage_record'),
    # 获取用户流转记录
    url(r'^getDrugRecordList/$', views.getDrugRecordList, name='getDrugRecordList'),
    # 申购提醒
    url(r'^getWantPurchaseList/$', views.getWantPurchaseList,
        name='getWantPurchaseList'),
    # 待入库提醒
    url(r'^getAcceptance/$', views.getAcceptance, name='getAcceptance'),
    # 报表数据统计数（今日入库，今日领用， 今日归还， 采购到货）
    url(r'^getStatisticalData/$', views.getStatisticalData, name='getStatisticalData'),
    # 库存量
    url(r'^getAllStockCount/$', views.getAllStockCount, name='getAllStockCount'),
    # 常用试剂
    url(r'^getOftenUse/$', views.getOftenUse, name='getOftenUse'),
    # 大屏页面
    url(r'^index/$', views.index, name='index'),
    # 获取预警Json数据
    url(r'getWarningListJson/', views.getWarningListJson, name='getWarningListJson'),
    # 获取温度echarts展示数据
    url(r'^getTemperatureEchartsJson/.*$', views.getTemperatureEchartsJson, name='getTemperatureEchartsJson'),

]

approve/urls.py
from django.conf.urls import url

from . import views

app_name = 'approve'

urlpatterns = [

    # 审批设置列表页面
    url(r'^setIndex/$', views.setIndex, name='setIndex'),
    # 我发起的页面
    url(r'^mySend/$', views.mySend, name='mySend'),
    # 待我审批页面
    url(r'^myReceive/$', views.myReceive, name='myReceive'),

    # 审批表单页面
    url(r'^approveForm/$', views.approveForm, name='approveForm'),
    # 查看审批页面
    url(r'^approveView/$', views.approveView, name='approveView'),
    # 审批设置表单页面
    url(r'^setForm/$', views.setForm, name='setForm'),


    # 获取我申请的审批信息数据
    url(r'^getMySendApproveInfoListJson/$', views.getMySendApproveInfoListJson, name='getMySendApproveInfoListJson'),
    # 获取待我审批的审批信息数据
    url(r'^getMyReceiveApproveInfoListJson/$', views.getMyReceiveApproveInfoListJson, name='getMyReceiveApproveInfoListJson'),
    # 获取审批类型数据列表
    url(r'^getApproveTypeListJson/$', views.getApproveTypeListJson, name='getApproveTypeListJson'),


    # 保存审批类型数据
    url(r'^saveApproveTypeData/$', views.saveApproveTypeData, name='saveApproveTypeData'),
    # 提交审批决定
    url(r'^summitApproveDecide/$', views.summitApproveDecide, name='summitApproveDecide'),
    # 删除审批类型数据
    url(r'^deleteApproveType/$', views.deleteApproveType, name='deleteApproveType'),

]

drug/urls.py
from django.conf.urls import url

from . import views

app_name = 'drug'

urlpatterns = [

    # 删除试剂处理路由
    url(r'deleteDrug/$', views.deleteDrug, name='deleteDrug'),
    # 获取扫码查询的数据
    url(r'GetDrugJson/$', views.GetDrugJson, name='GetDrugJson'),
    # 获取扫码查询信息并且称重
    url(r'GetDrugJsonAndWeight/$', views.GetDrugJsonAndWeight, name='GetDrugJsonAndWeight'),
    # 试剂类别请求路由
    url(r'drugTypeIndex/$', views.drugTypeIndex, name='drugTypeIndex'),
    # 获得试剂类别的JSON数据
    url(r'getDrugTypeListJson/$', views.getDrugTypeListJson, name='getDrugTypeListJson'),
    # 新增试剂类别
    url(r'createDrugType/$', views.createDrugType, name='createDrugType'),
    # 修改试剂类别
    url(r'(?P<varietyId>(\w{8}-\w{4}-\w{4}-\w{4}-\w{12}))/drugEditorTypeForm/$', views.drugEditorTypeForm, name='drugEditorTypeForm'),
    url(r'deleteDrugType/$', views.deleteDrugType, name='deleteDrugType'),
    #返回一维条码试剂入库iframe
    url(r'(?P<template_id>(\w{8}-\w{4}-\w{4}-\w{4}-\w{12}))/DrugPutInByBarCode/$', views.DrugPutInByBarCode, name='DrugPutInByBarCode'),
    # url(r'DrugPutInByBarCode/$', views.DrugPutInByBarCode, name='DrugPutInByBarCode'),
    # url(r'^(?P<template_id>(\w{8}-\w{4}-\w{4}-\w{4}-\w{12}))/RFIDStorage/$', views.RFIDStorage, name='RFIDStorage'),
    # 试剂归还路由处理
    url(r'drug_weigh/$', views.drug_weigh, name='drug_weigh'),
    # 天平去皮路由处理
    url(r'balance_tare/$', views.balance_tare, name='balance_tare'),
    # 获取指定试剂归还信息
    url(r'GetDrugInfo/$', views.GetDrugInfo, name='GetDrugInfo'),
    # 实现socket通讯
    url(r'drug_socket/$', views.drug_socket, name='drug_socket'),
    # 试剂禁止使用用户
    url(r'disabled_user/$', views.disabled_user, name='disabled_user'),
    # 保存禁用用户
    url(r'saveDisabledUser/$', views.saveDisabledUser, name='saveDisabledUser'),

    # 设置试剂空瓶
    url(r'setDrugEmpty/$', views.setDrugEmpty, name='setDrugEmpty'),
    # 设置试剂图片
    url(r'setDrugImageUrl/$', views.setDrugImageUrl, name='setDrugImageUrl'),



    #试剂入库视图
    url(r'drugPutInView/$', views.drugPutInView, name='drugPutInView'),
    #试剂领用视图
    url(r'^drugUseView/$', views.drugUseView, name='drugUseView'),
    #试剂归还视图
    url(r'^drugReturnView/$', views.drugReturnView, name='drugReturnView'),
    #获取待归还试剂
    url(r'^getWaitRetrunDrugList/$', views.getWaitRetrunDrugList, name='getWaitRetrunDrugList'),

    # 查询危险品
    url(r"^danger/$", views.danger, name='danger'),
]
# \w{8}-\w{4}-\w{4}-\w{4}-\w{12}

standard/keyCabinet/urls.py
from django.conf.urls import url

from . import views

app_name = 'keyCabinet'

urlpatterns = [
    # 检材入库页面
    url(r'^materialStockIn/$', views.materialStockIn, name='materialStockIn'),
    # 添加检材页面
    url(r'^addMaterialForm/$', views.addMaterialForm, name='addMaterialForm'),
    # 货架选择页面
    url(r'^shelfSelect/$', views.shelfSelect, name='shelfSelect'),
    # 钥匙柜选择页面
    url(r'^keyCabinetSelect/$', views.keyCabinetSelect, name='keyCabinetSelect'),
    # 钥匙柜查看页面
    url(r'^keyCabinetView/$', views.keyCabinetView, name='keyCabinetView'),
    # 货架领用页面
    url(r'^shelfUse/$', views.shelfUse, name='shelfUse'),
    # 货架归还页面
    url(r'^shelfReturn/$', views.shelfReturn, name='shelfReturn'),
    # 打印货架二维码页面
    url(r'^printFlowCode/$', views.printFlowCode, name='printFlowCode'),

    # 检材使用页面
    url(r'^materialUse/$', views.materialUse, name='materialUse'),
    # 检材归还页面
    url(r'^materialReturn/$', views.materialReturn, name='materialReturn'),
    # 试剂补货页面
    url(r'^materialSupply/$', views.materialSupply, name='materialSupply'),

    # 检材入库操作
    url(r'^materialStockInDo/$', views.materialStockInDo, name='materialStockInDo'),

    url(r'^getSupplyDrugCategoryListJson/$', views.getSupplyDrugCategoryListJson, name='getSupplyDrugCategoryListJson'),


        # 钥匙柜查看页面
    url(r'^mapFlowView/$', views.mapFlowView, name='mapFlowView'),
]

standard/urls.py
from django.conf.urls import url

from . import views

app_name = 'standard'

urlpatterns = [
    # 采购列表页面
    url(r'^purchaseIndex/$', views.purchaseIndex, name='purchaseIndex'),
    # 等待采购列表页面
    url(r'^purchaseWaitingIndex/$', views.purchaseWaitingIndex, name='purchaseWaitingIndex'),
    # 采购完成列表页面
    url(r'^purchaseCompleteIndex/$', views.purchaseCompleteIndex, name='purchaseCompleteIndex'),
    # 验收列表页面
    url(r'^acceptanceIndex/$', views.acceptanceIndex, name='acceptanceIndex'),
    # 期间核查列表页面
    url(r'^periodCheckIndex/$', views.periodCheckIndex, name='periodCheckIndex'),
    # 期间核查试剂列表页面
    url(r'^periodCheckDrugIndex/$', views.periodCheckDrugIndex, name='periodCheckDrugIndex'),
    # 即时期间核查页面
    url(r'^periodCheckDrugAnonIndex/$', views.periodCheckDrugAnonIndex, name='periodCheckDrugAnonIndex'),

    # 采购表单页面
    url(r'^purchaseForm/$', views.purchaseForm, name='purchaseForm'),
    # 采购试剂表单页面
    url(r'^purchaseDrugForm/$', views.purchaseDrugForm, name='purchaseDrugForm'),
    # 验收表单页面
    url(r'^acceptanceForm/$', views.acceptanceForm, name='acceptanceForm'),
    # 验收试剂表单页面
    url(r'^acceptanceDrugForm/$', views.acceptanceDrugForm, name='acceptanceDrugForm'),
    # 期间核查表单页面
    url(r'^periodCheckForm/$', views.periodCheckForm, name='periodCheckForm'),
    # 期间核查试剂表单页面
    url(r'^periodCheckDrugForm/$', views.periodCheckDrugForm, name='periodCheckDrugForm'),
    # 拍照上传表单页面
    url(r'^photographForm/$', views.photographForm, name='photographForm'),
    # 裁剪图片表单
    url(r'^cropperImgForm/$', views.cropperImgForm, name='cropperImgForm'),
    # 期间核查查看页面
    url(r'^periodCheckView/$', views.periodCheckView, name='periodCheckView'),
    # 试剂期间核查查看页面
    url(r'^periodCheckDrugDetailedInfo/$', views.periodCheckDrugDetailedInfo, name='periodCheckDrugDetailedInfo'),
    # 试剂期间核查不合适页面
    url(r'^periodCheckDrugFailureIndex/$', views.periodCheckDrugFailureIndex, name='periodCheckDrugFailureIndex'),

    
    # 采购查看页面
    url(r'^purchaseView/$', views.purchaseView, name='purchaseView'),
    # 验收查看页面
    url(r'^acceptanceView/$', views.acceptanceView, name='acceptanceView'),
    # 验收单PDF文件导出预览
    url(r'^acceptancePDFView/$', views.acceptancePDFView, name='acceptancePDFView'),
    # 采购单PDF文件导出预览
    url(r'^purchasePDFView/$', views.purchasePDFView, name='purchasePDFView'),


    # 联想搜索试剂
    url(r'^autoSearchDrugList/$', views.autoSearchDrugList, name='autoSearchDrugList'),
    # 获取采购单数据列表
    url(r'^getPurchaseOrderListJson/$', views.getPurchaseOrderListJson, name='getPurchaseOrderListJson'),
    # 获取验收单数据列表
    url(r'^getAcceptanceOrderListJson/$', views.getAcceptanceOrderListJson, name='getAcceptanceOrderListJson'),
    # 获取等待采购数据列表
    url(r'^getWaitingPurchaseListJson/$', views.getWaitingPurchaseListJson, name='getWaitingPurchaseListJson'),
    # 获取完成数据列表
    url(r'^getCompletePurchaseListJson/$', views.getCompletePurchaseListJson, name='getCompletePurchaseListJson'),
    # 获取期间核查数据列表
    url(r'^getPeriodCheckListJson/$', views.getPeriodCheckListJson, name='getPeriodCheckListJson'),
    # 获取期间核查详细数据列表
    url(r'^getPeriodCheckDetailedListJson/$', views.getPeriodCheckDetailedListJson, name='getPeriodCheckDetailedListJson'),
    # 获取期间核查不合格数据列表
    url(r'^getPeriodCheckFailureListJson/$', views.getPeriodCheckFailureListJson, name='getPeriodCheckFailureListJson'),

    # 保存采购数据
    url(r'^savePurchaseOrderData/$', views.savePurchaseOrderData, name='savePurchaseOrderData'),
    # 删除采购单
    url(r'^deletePurchaseOrder/$', views.deletePurchaseOrder, name='deletePurchaseOrder'),
    # 设置完成采购
    url(r'^setCompletePurchase/$', views.setCompletePurchase, name='setCompletePurchase'),
    # 保存拍照信息
    url(r'^savePhotographData/$', views.savePhotographData, name='savePhotographData'),
    # 保存验收单数据
    url(r'^saveAcceptanceOrderData/$', views.saveAcceptanceOrderData, name='saveAcceptanceOrderData'),
    # 保存期间核查数据
    url(r'^savePeriodCheckData/$', views.savePeriodCheckData, name='savePeriodCheckData'),
    # 保存期间核查详细数据
    url(r'^savePeriodCheckDetailedData/$', views.savePeriodCheckDetailedData, name='savePeriodCheckDetailedData'),
    # 导出PDF
    url(r'^exportPDF/$', views.exportPDF, name='exportPDF'),
]

user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    # 用户页面
    url(r'^index/', views.index, name='index'),
    # 获取用户列表
    url(r'^getUserListJson/$', views.getUserListJson, name='getUserListJson'),
    # 获取角色列表
    url(r'^getRoleListJson/$', views.getRoleListJson, name='getRoleListJson'),
    # 用户表单页面

    url(r'^form/.*?$', views.user_form, name='form'),
    # 用户权限表单页面
    url(r'^importForm/$', views.user_importForm, name='importForm'),
    # 保存用户新增或修改数据
    url(r'^saveUserData/$', views.saveUserData, name='saveUserData'),
    # 删除用户操作
    url(r'^deleteUser/$', views.deleteUser, name='deleteUser'),
    # 锁定用户
    url(r'^lockUser/$', views.lockUser, name='lockUser'),
    # 获取用户功能权限页面
    url(r'^(?P<user_id>(\w{8}-\w{4}-\w{4}-\w{4}-\w{12}))/powerForm/$', views.powerForm, name='powerForm'),
    # 修改用户功能数据
    url(r'^savePowerData/$', views.savePowerData, name='savePowerData'),
    # 用户点击打印条码处理路由
    url(r'^printer_user_code/$', views.printer_user_code, name='printer_user_code'),

    # 用户角色列表页面
    url(r'^roleIndex/', views.roleIndex, name='roleIndex'),
    # 用户角色表单页面
    url(r'^roleForm/', views.roleForm, name='roleForm'),
    # 保存角色数据
    url(r'^saveRoleData/$', views.saveRoleData, name='saveRoleData'),
    # 删除角色操作
    url(r'^deleteRole/$', views.deleteRole, name='deleteRole'),

]

standard/keyCabinet/models.py
from django.db import models

# Create your models here.

standard/models.py
from django.db import models

# Create your models here.

templates/standard/periodCheckDrugFailureIndex.html
{% extends 'baseBZP.html' %}

{% block content %}

{% load static %}

<div class="layui-fluid">
    <div class="layui-card">
      <div class="layui-form layui-card-header layuiadmin-card-header-auto">
        <div class="layui-form-item">
          <div class="layui-inline">
            <label class="layui-form-label">编号</label>
            <div class="layui-input-block">
              <input type="text" name="BarCode" placeholder="请输入" autocomplete="off" class="layui-input">
            </div>
          </div>
          <div class="layui-inline">
            <label class="layui-form-label">试剂名称</label>
            <div class="layui-input-block">
              <input type="text" name="Name" placeholder="请输入" autocomplete="off" class="layui-input">
            </div>
          </div>
          <div class="layui-inline">
            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="LAY-user-front-search">
              <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
            </button>
          </div>
        </div>
      </div>
      
      <div class="layui-card-body">
        <!-- <div style="padding-bottom: 10px;">
          <button class="layui-btn layuiadmin-btn-useradmin" data-type="add">新增期间核查</button>
        </div> -->
        
        <table id="LAY-datatable" lay-filter="LAY-datatable"></table>
        <script type="text/html" id="progressTpl">
          {% verbatim %} 
          <div class="layui-progress layuiadmin-order-progress" lay-filter="progress-"+ {{ d.PeriodCheckId }} +"">
            <div class="layui-progress-bar layui-bg-blue" lay-percent= "{{ (d.PeriodCurrentDrugCount- d.NotPeriodCheckTotalCount) / d.PeriodCurrentDrugCount * 100  }}%" style="width: {{ (d.PeriodCurrentDrugCount- d.NotPeriodCheckTotalCount) / d.PeriodCurrentDrugCount * 100  }}%;"></div>
          </div>
          {% endverbatim %} 
        </script>
        <script type="text/html" id="specTpl">
          {% verbatim %} 
          {{d.Speci+d.SpeciUnit}}
          {% endverbatim %}
      </script> 
        <script type="text/html" id="statusTpl">
            {% verbatim %} 
            {{#  if(d.PeriodCheckStatus==2){ }}
              <button class="layui-btn layui-btn-normal layui-btn-xs">已结束</button>
            {{#  } else { }}
              <button class="layui-btn layui-btn-primary layui-btn-xs">进行中</button>
            {{#  } }}
            {% endverbatim %}
        </script> 
        <script type="text/html" id="datatable-toolbar">
          <a class="layui-btn layui-btn-warm layui-btn-xs" lay-event="check"><i class="layui-icon layui-icon-list"></i>查看</a>
          <!-- <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>编辑</a> -->
        </script>
      </div>
    </div>
  </div>
  <script>
  layui.use(['index', 'table'], function(){
    var table = layui.table
    ,form = layui.form;

    //列表数据
    table.render({
        elem: '#LAY-datatable'
        ,url: "{% url 'standard:getPeriodCheckFailureListJson' %}"
        ,size:'lg'
        ,cols: [[
        {type: 'checkbox', fixed: 'left'}
        ,{field: 'BarCode', width: 120, title: '编号'}
        ,{field: 'Name', title: '试剂名称'}
        ,{field: 'CASNumber', width: 120, title: 'CAS码'}
        ,{field: 'Speci', width: 120, title: '规格'}
        ,{field: 'Purity', width: 120, title: '纯度'}
        ,{field: 'CreateDate', width: 230, title: '核查时间'}
        ,{field: 'PeriodCheckMethod', width: 180, title: '核查方法'}
        ,{field: 'Description', width: 180, title: '描述'}
        ,{title: '操作', width: 200, minWidth: 200, align: 'center', fixed: 'right', toolbar: '#datatable-toolbar'}
        ]]
        ,page: {
          layout: [ 'count', 'prev', 'page', 'next',] //自定义分页布局
          ,prev:'上一页'
          ,next:'下一页'
        }
        ,limit: 15
        ,limits: [10, 15, 20, 25, 30]
        ,height: 'full-130'
    });
    
    //监听工具条
    table.on('tool(LAY-datatable)', function(obj){
        var data = obj.data;
        if(obj.event === 'del'){
          top.layer.prompt({
            formType: 1
            ,title: '敏感操作，请验证密码'
        }, function(value, index){
            top.layer.close(index);
            if(hex_md5(value)!=top.CheckCode)
            {
                top.layer.msg("验证失败！");
                return
            }
            top.layer.confirm('确定删除吗？', function(index) {
                //提交
                $.post("{% url 'user:deleteUser' %}", {deleteIds:data.UserId}, function (obj) {
                    if (obj.status == 1) {
                        top.layer.msg("删除成功", function () {
                            top.layer.close(index);
                        });
                    }
                    else {
                        top.layer.msg("删除失败 " + obj.message);
                    }
                });
                obj.del();
                // table.reload('LAY-datatable');
            });
        });
        } else if(obj.event === 'edit'){
        var tr = $(obj.tr);

        top.layer.open({
          type: 2
          ,title: '编辑期间核查'
          ,content: "{% url 'standard:periodCheckForm' %}?VarietyId="+data.VarietyId
          ,area: ['1200px', '650px']
          ,btn: ['确定', '取消']
          ,yes: function(index, layero){
            var submitID = 'LAY-user-front-submit'
            ,submit = layero.find('iframe').contents().find('#'+ submitID);
            submit.trigger('click');
          }        
          ,end:function(){
            table.reload('LAY-datatable'); //数据刷新
          }
        }); 
        }
        else if(obj.event === 'check'){
        var tr = $(obj.tr);

        top.layer.open({
            type: 2
            ,title: '核查试剂信息'
            ,content: "{% url 'standard:periodCheckDrugForm' %}?DrugCode="+data.BarCode+"&PeriodCheckId="+data.PeriodCheckId
            ,area: ['600px', '430px']
            ,shade: [0.9, '#000']
            ,yes: function(index, layero){
              top.layer.close(index);
              table.reload('LAY-datatable'); //数据刷新
            }        
            ,end:function(){
                table.reload('LAY-datatable'); //数据刷新
            }
        }); 
        }
        else if(obj.event === 'view'){
        var tr = $(obj.tr);
        top.layer.open({
          type: 2
          ,title: '查看期间核查信息'
          ,content: "{% url 'standard:periodCheckView' %}?VarietyId="+data.VarietyId
          ,area: ['1200px', '600px']
          ,yes: function(index, layero){
            var submitID = 'LAY-user-front-submit'
            ,submit = layero.find('iframe').contents().find('#'+ submitID);
            submit.trigger('click');
          }        
          ,end:function(){
            table.reload('LAY-datatable'); //数据刷新
          }
        }); 
        }
    });
    
    //监听搜索
    form.on('submit(LAY-user-front-search)', function(data){
      var field = data.field;
      
      //执行重载
      table.reload('LAY-datatable', {
        where: field
      });
    });
  
    //事件
    var active = {
      batchdel: function(){
        var checkStatus = table.checkStatus('LAY-datatable')
        ,checkData = checkStatus.data; //得到选中的数据

        if(checkData.length === 0){
          return layer.msg('请选择数据');
        }
        
        top.layer.prompt({
          formType: 1
          ,title: '敏感操作，请验证密码'
        }, function(value, index){
          top.layer.close(index);
          if(hex_md5(value)!=top.CheckCode)
          {
            top.layer.msg("验证失败！");
            return
          }
          top.layer.confirm('确定删除吗？', function(index) {
            var deleteIds='';
            checkData.forEach(function(element,index){
                if(deleteIds!=''){deleteIds+=','}
                deleteIds+=element.UserId;
            });
            //提交
            $.post("{% url 'user:deleteUser' %}", {deleteIds:deleteIds}, function (obj) {
                if (obj.status == 1) {
                    top.layer.msg("删除成功", function () {
                        table.reload('LAY-datatable');
                        top.layer.close(index);
                    });
                }
                else {
                    top.layer.msg("删除失败 " + obj.message);
                }
            });
            
          });
        });
      }
      ,add: function(){
        top.layer.confirm('确定要新增期间核查吗？', function(index) {
          //提交
          $.post("{% url 'standard:savePeriodCheckData' %}", function (obj) {
              if (obj.status == 1) {
                  top.layer.msg("新增成功", function () {
                      table.reload('LAY-datatable');
                      top.layer.close(index);
                  });
              }
              else {
                  top.layer.msg("新增失败 " + obj.message);
              }
            });
            
        });
      }
    };
    
    $('.layui-btn.layuiadmin-btn-useradmin').on('click', function(){
      var type = $(this).data('type');
      active[type] ? active[type].call(this) : '';
    });

  });
  </script>
<iframe width=0 height=0 frameborder=0 id="export" />
{% endblock %}