TY_RMS_Multiple_Manage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'multiple'

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^main/', views.main, name='main'),
    url(r'^user/', include('user.urls')),
    url(r'^drug/', include('drug.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^warning/', include('warning.urls')),
    url(r'^humiture/', include('humiture.urls')),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^dataReport/', include('dataReport.urls')),
    url(r'^drugTemplate/', include('drugTemplate.urls')),
    url(r'^stockTaking/', include('stockTaking.urls')),
    url(r'^version/', include('version.urls')),
    url(r'^approve/', include('approve.urls')),
    url(r'^standard/', include('standard.urls')),

    # 危化品
    url(r'^Hazardous/', include('Hazardous.urls')),

    url(r'^keyCabinet/', include('keyCabinet.urls')),

    # 登录
    url(r'^account/login/$', views.account_login, name='account_login'),
    url(r'^account/barcode/$', views.account_barcode, name='account_barcode'),
    # 退出系统
    url(r'^account/logout/$', views.account_logout, name='account_logout'),
    # 试剂扫码查询
    url(r'^drug/scanBarCode/$', views.drug_scanBarCode, name='drug_scanBarCode'),
    # 试剂列表首页
    url(r'^drug/index/$', views.drug_index, name='drug_index'),
    # 编辑试剂表单页面
    url(r'^drug/form/$', views.drug_form, name='drug_form'),
    # 试剂表单页面
    url(r'^drug/drugTypeForm/$', views.drug_drugTypeForm, name='drug_drugTypeForm'),
    # 获取试剂类型列表json处理url
    url(r'^drug/GetDrugListJson/$', views.drug_GetDrugListJson, name='drug_GetDrugListJson'),
    # 获取试剂类型的JSON数据
    url(r'^drug/GetDrugTypeListJson/$', views.drug_GetDrugTypeListJson, name='drug_GetDrugTypeListJson'),
    # 试剂模板页面首页
    url(r'^drugTemplate/index/$', views.drugTemplate_index, name='drugTemplate_index'),
    # 新增试剂模板
    url(r'^drugTemplate/form/$', views.drugTemplate_form, name='drugTemplate_form'),
    # 修改试剂
    url(r'^drugTemplate/(?P<template_id>.*)/update_form/$', views.drugTemplate_update_form, name='drugTemplate_update_form'),
    # 新增单次模板条目
    url(r'^drugTemplate/itemForm/$', views.drugTemplate_itemForm, name='drugTemplate_itemForm'),
    # 新增模板视图路由
    url(r'^drugTemplate/SaveTemplateData/$', views.drugTemplate_saveTemplateData, name='drugTemplate_saveTemplateData'),
    # 获取访问入库模板JSON数据
    url(r'^drugTemplate/getTemplateListJson/$', views.drugTemplate_getTemplateListJson, name='drugTemplate_getTemplateListJson'),
    # 获取ClientId Json数据
    url(r'^drugTemplate/ClientListJson/$', views.drugTemplate_clientListJson, name='drugTemplate_clientListJson'),
    # 删除模板
    url(r'^drugTemplate/deleteTemplate/$', views.drugTemplate_deleteTemplate, name='drugTemplate_deleteTemplate'),
    # 日志列表首页
    url(r'^log/index/$', views.log_index, name='log_index'),
    #mxh_试剂详细信息统计
    url(r'dataReport/drug_GetDrugListJson/$',views.drug_GetDrugListJson,name='drug_GetDrugListJson'),
    # 首页试剂记录页面
    url(r'^home/(?P<drug_id>.*)/homeDrugRecord/$', views.home_homeDrugRecord, name='home_homeDrugRecord'),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'TY_RMS_Multiple_Manage.views.page_not_found'

api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [

    # 获取试剂Json数据
    url(r'^getDrugList/$', views.getDrugList, name='getDrugList'),

    # 获取用户列表
    url(r'^getUserList/$', views.getUserList, name='getUserList'),
    url(r'^form_total/', views.form_total, name='form_total'),
    url(r'^usage_record/', views.usage_record, name='usage_record'),
    # 获取用户流转记录
    url(r'^getDrugRecordList/$', views.getDrugRecordList, name='getDrugRecordList'),
    # 申购提醒
    url(r'^getWantPurchaseList/$', views.getWantPurchaseList,
        name='getWantPurchaseList'),
    # 待入库提醒
    url(r'^getAcceptance/$', views.getAcceptance, name='getAcceptance'),
    # 报表数据统计数（今日入库，今日领用， 今日归还， 采购到货）
    url(r'^getStatisticalData/$', views.getStatisticalData, name='getStatisticalData'),
    # 库存量
    url(r'^getAllStockCount/$', views.getAllStockCount, name='getAllStockCount'),
    # 常用试剂
    url(r'^getOftenUse/$', views.getOftenUse, name='getOftenUse'),
    # 大屏页面
    url(r'^index/$', views.index, name='index'),
    # 获取预警Json数据
    url(r'getWarningListJson/', views.getWarningListJson, name='getWarningListJson'),
    # 获取温度echarts展示数据
    url(r'^getTemperatureEchartsJson/.*$', views.getTemperatureEchartsJson, name='getTemperatureEchartsJson'),

]

dataReport/urls.py
from django.conf.urls import url

from dataReport import views

app_name = 'dataReport'

urlpatterns = [
    # 数据报表首页
    url(r'^index/$', views.index, name='index'),
    # 数据报表（试剂流转记录）
    url(r'^drugRecordList/$', views.drugRecordList, name='drugRecordList'),
    # 数据报表（预警列表）
    url(r'^warningList/$', views.warningList, name='warningList'),
    # 获取预警列表Json数据
    url(r'^getWarningListJson/$', views.getWarningListJson, name='getWarningListJson'),
    # 数据报表（试剂报纸列表）
    url(r'^drugShelfLifeList/$', views.drugShelfLifeList, name='drugShelfLifeList'),
    # 数据报表（用户数据列表）
    url(r'^userList/$', views.userList, name='userList'),
    # 数据报表（用户数据列表）
    url(r'^categoryCountList/$', views.categoryCountList, name='categoryCountList'),
    # 获取客户端信息
    url(r'^getClientListJson/$', views.getClientListJson, name='getClientListJson'),
    #得到操作类型
    url(r'getRecordType/$',views.getRecordType,name='getRecordType'),
    # 数据流转记录数据
    url(r'^getDrugRecordListJson/.*$', views.getDrugRecordListJson, name='getDrugRecordListJson'),
    # 获取流转记录图表
    url(r'^drugRecordChart/$', views.drugRecordChart, name='drugRecordChart'),
    # 获取库存信息概览统计Json数据
    url(r'^getCategoryCountListJson/$', views.getCategoryCountListJson, name='getCategoryCountListJson'),
    # 获取试剂Json数据列表
    url(r'^getDrugListJson/.*$', views.getDrugListJson, name='getDrugListJson'),
    # 试剂保质期统计图
    url(r'^drugShelfLifeChart/$', views.drugShelfLifeChart, name='drugShelfLifeChart'),
    # 获取试剂的Json数据
    url(r'^getDrugShelfLifeChartJson/$', views.getDrugShelfLifeChartJson, name='getDrugShelfLifeChartJson'),
    # 获取试剂资金消耗页面
    url(r'^fundsConsumeChart/$', views.fundsConsumeChart, name='fundsConsumeChart'),
    #  获取试剂资金消耗统计
    url(r'^getFundsConsumeChartJson/$', views.getFundsConsumeChartJson, name='getFundsConsumeChartJson'),
    # 获取试剂库存价值图标
    url(r'^fundsNormalChart/$', views.fundsNormalChart, name='fundsNormalChart'),
    # 获取试剂库存价值Json数据
    url(r'^getFundsNormalChartJson/$', views.getFundsNormalChartJson, name='getFundsNormalChartJson'),
    # 获取试剂流转记录表
    url(r'^getDrugRecordChartJson/$', views.getDrugRecordChartJson, name='getDrugRecordChartJson'),
    # 导出库存试剂信息报表路由
    url(r'^ExportDrugCategoryData/$', views.ExportDrugCategoryData, name='ExportDrugCategoryData'),
    # 导出试剂数据明细报表
    url(r'^exportDrugShelfLifeData/.*?$', views.exportDrugShelfLifeData, name='exportDrugShelfLifeData'),
    # 导出试剂流转记录报表路由
    url(r'^exportDrugRecordData/.*?$', views.exportDrugRecordData, name='exportDrugRecordData'),
    # 导出系统预警数据记录报表
    url(r'^exportWarningData/$', views.exportWarningData, name='exportWarningData'),
    # 导出用户角色统计报表
    url(r'^exportUserData/$', views.exportUserData, name='exportUserData'),
    # 导出报表统计下的所有报表数据 路由
    url(r'^exportAllReportData/$', views.exportAllReportData, name='exportAllReportData'),

    #######################################返回页面#########################
    #库存信息总览
    url(r'^getOverviewInfo/$', views.getOverviewInfo, name='getOverviewInfo'),
    #入库信息查询
    url(r'^getPutInInfo/$', views.getPutInInfo, name='getPutInInfo'),
    #使用频率统计
    url(r'^getUseFrequencyInfo/$', views.getUseFrequencyInfo, name='getUseFrequencyInfo'),
    #消耗统计
    url(r'^getDrugConsumeInfo/$', views.getDrugConsumeInfo, name='getDrugConsumeInfo'),
    #保质期统计
    url(r'^getShelflifeInfo/$', views.getShelflifeInfo, name='getShelflifeInfo'),
    #保质期预警统计
    url(r'^getShelflifeWarning/$', views.getShelflifeWarning, name='getShelflifeWarning'),
    #库存呆滞料统计
    url(r'^getStagnantInfo/$', views.getStagnantInfo, name='getStagnantInfo'),
    #试剂历史使用信息统计
    url(r'^getDrugUseRecordInfo/$', views.getDrugUseRecordInfo, name='getDrugUseRecordInfo'),


    #人员用量统计
    url(r'^getUserConsumeInfo/$', views.getUserConsumeInfo, name='getUserConsumeInfo'),
    #试剂种类消耗统计
    url(r'^getDrugUseCategotyConsumeInfo/$', views.getDrugUseCategotyConsumeInfo, name='getDrugUseCategotyConsumeInfo'),
    #试剂明细信息统计
    url(r'^getDrugDetailInfo/$', views.getDrugDetailInfo, name='getDrugDetailInfo'),

    ##################################返回数据##############################
    #返回库存总览json数据
    url(r'^getOverviewInfoJson/$', views.getOverviewInfoJson, name='getOverviewInfoJson'),
    #返回入库信息json数据
    url(r'^getPutInInfoJson/$', views.getPutInInfoJson, name='getPutInInfoJson'),
    #返回使用频率json数据
    url(r'^getUseFrequencyInfoJson/$', views.getUseFrequencyInfoJson, name='getUseFrequencyInfoJson'),
    #返回消耗统计json数据
    url(r'^getDrugConsumeInfoJson/$', views.getDrugConsumeInfoJson, name='getDrugConsumeInfoJson'),
    #返回保质期统计json数据
    url(r'^getShelflifeInfoJson/$', views.getShelflifeInfoJson, name='getShelflifeInfoJson'),
    #返回保质期预警统计json数据
    url(r'^getShelflifeWarningJson/$', views.getShelflifeWarningJson, name='getShelflifeWarningJson'),
    #返回库存呆滞json数据
    url(r'^getStagnantInfoJson/$', views.getStagnantInfoJson, name='getStagnantInfoJson'),
    #返回试剂历史使用json数据
    url(r'^getDrugUseRecordInfoJson/$', views.getDrugUseRecordInfoJson, name='getDrugUseRecordInfoJson'),

    #返回人员用量统计json数据
    url(r'^getUserConsumeInfoJson/$', views.getUserConsumeInfoJson, name='getUserConsumeInfoJson'),
    #返回试剂种类消耗统计json数据
    url(r'^getDrugUseCategotyConsumeInfoJson/$', views.getDrugUseCategotyConsumeInfoJson, name='getDrugUseCategotyConsumeInfoJson'),
    #返回试剂明细信息统计json数据
    url(r'^getDrugDetailInfoJson/$', views.getDrugDetailInfoJson, name='getDrugDetailInfoJson'),

    #####################################下载报表#################################
    #下载库存总览表
    url(r'^downOverviewInfo/$', views.downOverviewInfo, name='downOverviewInfo'),
    #下载入库信息表
    url(r'^downPutInInfo/$', views.downPutInInfo, name='downPutInInfo'),
    #下载使用频率报表
    url(r'^downUseFrequencyInfo/$', views.downUseFrequencyInfo, name='downUseFrequencyInfo'),
    #下载消耗统计报表
    url(r'^downDrugConsumeInfo/$', views.downDrugConsumeInfo, name='downDrugConsumeInfo'),
    #下载保质期统计报表
    url(r'^downShelflifeInfo/$', views.downShelflifeInfo, name='downShelflifeInfo'),
    #下载保质期预警统计报表
    url(r'^downShelflifeWarning/$', views.downShelflifeWarning, name='downShelflifeWarning'),
    #下载库存呆滞表
    url(r'^downStagnantInfo/$', views.downStagnantInfo, name='downStagnantInfo'),
    #下载试剂历史使用表
    url(r'^downDrugUseRecordInfo/$', views.downDrugUseRecordInfo, name='downDrugUseRecordInfo'),
    #下载人员用量统计报表
    url(r'^downUserConsumeInfo/$', views.downUserConsumeInfo, name='downUserConsumeInfo'),
    #下载试剂种类消耗统计报表
    url(r'^downDrugUseCategotyConsumeInfo/$', views.downDrugUseCategotyConsumeInfo, name='downDrugUseCategotyConsumeInfo'),
    #下载人员消耗试剂信息统计报表
    url(r'^downUserConsumeInfoJson/$', views.downUserConsumeInfoJson,name='downUserConsumeInfoJson'),
    #下载试剂种类消耗信息统计报表
    url(r'^downDrugUseCategotyConsumeInfoJson/$', views.downDrugUseCategotyConsumeInfoJson,name='downDrugUseCategotyConsumeInfoJson'),



]

user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    # 用户页面
    url(r'^index/', views.index, name='index'),
    # 获取用户列表
    url(r'^getUserListJson/$', views.getUserListJson, name='getUserListJson'),
    # 获取角色列表
    url(r'^getRoleListJson/$', views.getRoleListJson, name='getRoleListJson'),
    # 用户表单页面

    url(r'^form/.*?$', views.user_form, name='form'),
    # 用户权限表单页面
    url(r'^importForm/$', views.user_importForm, name='importForm'),
    # 保存用户新增或修改数据
    url(r'^saveUserData/$', views.saveUserData, name='saveUserData'),
    # 删除用户操作
    url(r'^deleteUser/$', views.deleteUser, name='deleteUser'),
    # 锁定用户
    url(r'^lockUser/$', views.lockUser, name='lockUser'),
    # 获取用户功能权限页面
    url(r'^(?P<user_id>(\w{8}-\w{4}-\w{4}-\w{4}-\w{12}))/powerForm/$', views.powerForm, name='powerForm'),
    # 修改用户功能数据
    url(r'^savePowerData/$', views.savePowerData, name='savePowerData'),
    # 用户点击打印条码处理路由
    url(r'^printer_user_code/$', views.printer_user_code, name='printer_user_code'),

    # 用户角色列表页面
    url(r'^roleIndex/', views.roleIndex, name='roleIndex'),
    # 用户角色表单页面
    url(r'^roleForm/', views.roleForm, name='roleForm'),
    # 保存角色数据
    url(r'^saveRoleData/$', views.saveRoleData, name='saveRoleData'),
    # 删除角色操作
    url(r'^deleteRole/$', views.deleteRole, name='deleteRole'),

]

templates/dataReport - ¸±±¾/categoryCountList.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
        .chosen-container-single .chosen-single {
        height: 25px !important;
        line-height: 25px !important;
        padding-top: 2px !important;
    }
</style>
<div class="wrapper wrapper-content animated fadeInDown">
    <div class="mail-box-header">
        <form method="get" class="pull-right mail-search" accept-charset="UTF-8">
            <div class="input-group">
                <input type="text" class="form-control" id="searchValue" name="searchValue" placeholder="搜索试剂名称">
                    <div class="input-group-btn">
                        <button type="button" id="btnTableSearch" class="btn btn-primary" >
                            搜索
                        </button>
                    </div>
            </div>
        </form>
        <h2>
            库存试剂信息概览统计
        </h2>
        <div class="mail-tools tooltip-demo m-t-md">
            <div class="btn-group pull-right">
                <a type="submit" class="btn btn-primary btn-sm" href="{% url 'dataReport:index' %}">
                    返回统计目录
                </a>
            </div>
            <button class="btn btn-white btn-sm pull-left" style="margin-right:3px;" data-toggle="tooltip" id="btnTableReload" data-placement="left" title="刷新统计列表"><i class="fa fa-refresh"></i> 刷新</button>
            <button class="btn btn-white btn-sm pull-left" style="margin-right:3px;" data-toggle="tooltip" id="btnTableExport" data-placement="left" title="导出报表统计列表"><i class="fa fa-download"></i> 导出报表</button>
            <button class="btn btn-white btn-sm pull-left" style="margin-right:3px;" data-toggle="tooltip" id="btnTableChart1" data-placement="left" title="以图表形式显示统计数据"><i class="fa fa-pie-chart"></i> 试剂资金消耗图表统计</button>
            <button class="btn btn-white btn-sm pull-left" style="margin-right:3px;" data-toggle="tooltip" id="btnTableChart2" data-placement="left" title="以图表形式显示统计数据"><i class="fa fa-pie-chart"></i> 试剂库存价值图表统计</button>
           <!-- <div class="input-daterange input-group date pull-left" style="width:300px;">
                <span class="input-group-addon"> &nbsp;&nbsp;药柜：</span>
                <select data-placeholder="选择所属药柜..." id="cabinetSelect" required="required" class="chosen-select" style="width:200px;height:20px">
                    <option value="">全部</option>
                </select>
            </div> -->
            <div style="clear:both"></div>
        </div>
    </div>
    <div class="ibox-content">
        <table id="dataTableModel" style="width:800px" class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
                <tr>
                    <th width="100">试剂类别</th>
                    <th width="50">纯度</th>
                    <th width="100">CAS码</th>
                    <th width="60">重点监控</th>
                    <th width="80">当前库存总量</th>
                    <th width="80">当前在库数量</th>
                    <th width="80">当前借出数量</th>
                    <th width="120">当前库存价值（元）</th>
                    <th width="120">季度历史入库总量</th>
                    <th width="80">季度消耗总量</th>
                    <th width="120">季度消耗价值（元）</th>
                    <th width="120">年度历史入库总量</th>
                    <th width="80">年度消耗总量</th>
                    <th width="120">年度消耗价值（元）</th>
                </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
                <tr>
                    <th>试剂类别</th>
                    <th>纯度</th>
                    <th>CAS码</th>
                    <th>重点监控</th>
                    <th>当前库存总量</th>
                    <th>当前在库数量</th>
                    <th>当前借出数量</th>
                    <th>当前库存价值（元）</th>
                    <th>季度历史入库总量</th>
                    <th>季度消耗总量</th>
                    <th>季度消耗价值（元）</th>
                    <th>年度历史入库总量</th>
                    <th>年度消耗总量</th>
                    <th>年度消耗价值（元）</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
    {% load static %}
    <script src="{% static 'js/fileDownload.js' %}"></script>
    <script src="{% static 'js/warning.js' %}"></script>

<script type="text/javascript">

    $(function () {
        /* $.get('', function (obj) {
            $(obj.data).each(function (index, data) {
                $("#cabinetSelect").append("<option value='" + data.ClientId + "' hassubinfo='true'>" + data.ClientName + "</option>");
            });
            $(".chosen-select").chosen({
                no_results_text: "没有找到",
                disable_search: true,
                allow_single_deselect: true
            });
        }); */
        var tableModel = $('#dataTableModel').DataTable({
            //searching: false,
            lengthChange: false,
            select: true,
            "scrollX": true,
            ajax: {
                url: '{% url 'dataReport:getCategoryCountListJson' %}',
                data: {},
                dataSrc: 'data',
            },

            columns: [
            { data: 'Name' },
            { data: 'Purity' },
            { data: 'CASNumber' },
            { data: 'IsSupervise' },
            { data: 'TotalCount' },
            { data: 'NormalCount' },
            { data: 'UseCount' },
            { data: 'StockPrice' },
            { data: 'QuarterlyPutInCount' },
            { data: 'QuarterlyEmptyCount' },
            { data: 'QuarterlyEmptyPrice' },
            { data: 'YearPutInCount' },
            { data: 'YearEmptyCount' },
            { data: 'YearEmptyPrice' }
            ],
            createdRow: function(row, data, dataIndex){
                $(row).children('td').eq(3).html(formatIsSupervise(data.IsSupervise));
                $(row).children('td').eq(4).html(transition_None(data.TotalCount));
                $(row).children('td').eq(6).html(transition_None(data.UseCount));
                $(row).children('td').eq(7).html(transition_None(data.StockPrice));
                $(row).children('td').eq(10).html(transition_None(data.QuarterlyEmptyPrice));
                $(row).children('td').eq(13).html(transition_None(data.YearEmptyPrice));
            }

        });
        $("#btnTableChart1").click(function () {
            quiteTime = Infinity;
            parent.layer.open({
                title: "试剂资金消耗图表统计",
                shift: 2,
                type: 2,
                area: ['850px', '650px'],
                
                content: ['{% url 'dataReport:fundsConsumeChart' %}', 'no'],
                end: function () {
                    currentTime = 0;
                    quiteTime = 600;
                    tableModel.ajax.reload();
                }
            });
        });
        $("#btnTableChart2").click(function () {
            quiteTime = Infinity;
            parent.layer.open({
                title: "试剂库存价值图表统计",
                shift: 2,
                type: 2,
                area: ['850px', '650px'],
                
                content: ['{% url 'dataReport:fundsNormalChart' %}', 'no'],
                end: function () {
                    currentTime = 0;
                    quiteTime = 600;
                    tableModel.ajax.reload();
                }
            });
        });
        $("#btnTableSearch").click(function () {

            tableModel.search($("#searchValue").val()).draw();
        });
        $("#searchValue").keyup(function () {
            tableModel.search($("#searchValue").val()).draw();

        })
        $("#btnTableReload").click(function () {
            location.href = '{% url 'dataReport:categoryCountList' %}';
        });

        $("#tablePre").click(function () {
            $("#dataTableModel_previous").click();

        });

        $("#tableNext").click(function () {
            $("#dataTableModel_next").click();

        });
        $("#btnTableExport").click(function () {
            index = '';
            var url = '{% url 'dataReport:ExportDrugCategoryData' %}';
            $.fileDownload(url, {
                httpMethod: 'GET',
                prepareCallback: function (url) {
                    index = parent.layer.load(2)
                },
                successCallback: function (url) {
                    parent.layer.close(index)
                },
                 failCallback: function (url) {
                     msg('数据异常, 下载失败');
                     parent.layer.close(index)
                 }
            })
        });
        $('#searchValue').focus(function () {
            $(this).keydown(function () {
                switch (event.keyCode) {
                    case 13:
                        return false;
                }
            })
        });



        function transition_None(params) {

            switch (params) {
                case null:
                    return 0;

            }
        }

        function formatIsSupervise(params) {
            switch (params) {
                case 0:
                    return '否';
                case 1:
                    return '是';
                default:
                    return '否'
            }
        }

    });
</script>
<iframe width=0 height=0 frameborder=0 id="export" />


{% endblock %}

templates/dataReport - ¸±±¾/drugShelfLifeChart.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
<script src="{% static 'js/plugins/echarts/echarts.min.js' %}"></script>
<script src="{% static 'js/plugins/echarts/shine.js' %}"></script>
<script src="{% static 'js/utils.js' %}"></script>
                    <script src="{% static 'js/warning.js' %}"></script>

<style type="text/css">
    body {
        background-color: #FFF !important;
    }
</style>
<div class="echarts" id="echarts" style="width:100%;height:100%;padding:20px"></div>

<script type="text/javascript">
    $(function () {
        var lineChart = echarts.init(document.getElementById("echarts"), "shine");
        $.get('{% url 'dataReport:getDrugShelfLifeChartJson' %}', function (obj) {
            var option = {
                title: {
                    text: '试剂保质期统计',
                    subtext: '',
                    x: 'center'
                },
                tooltip: {
                    trigger: 'item',
                    formatter: "{a} <br/>{b} : {c}个 ({d}%)"
                },
                legend: {
                    orient: 'vertical',
                    left: 'left',
                    data: obj.data.legend
                },
                series: [
                    {
                        name: '保质期',
                        type: 'pie',
                        radius: '55%',
                        center: ['50%', '60%'],
                            data: obj.data.data,
                        itemStyle: {
                            emphasis: {
                                shadowBlur: 10,
                                shadowOffsetX: 0,
                                shadowColor: 'rgba(0, 0, 0, 0.5)'
                            }
                        }
                    }
                ]
            };
            var lineoption = option;
            lineChart.setOption(lineoption);
            $(window).resize(lineChart.resize);
        });
    })
</script>

{% endblock %}

templates/dataReport - ¸±±¾/drugShelfLifeChart1.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
<script src="{% static 'js/plugins/echarts/echarts.min.js' %}"></script>
<script src="{% static 'js/plugins/echarts/shine.js' %}"></script>
<script src="{% static 'js/utils.js' %}"></script>
                    <script src="{% static 'js/warning.js' %}"></script>

<style type="text/css">
    body {
        background-color: #FFF !important;
    }
</style>
<div class="echarts" id="echarts" style="width:100%;height:100%;padding:20px"></div>

<script type="text/javascript">
    $(function () {
        var lineChart = echarts.init(document.getElementById("echarts"), "shine");
        $.get('{% url 'dataReport:getDrugShelfLifeChartJson' %}', function (obj) {
            var option = {
                title: {
                    text: '试剂保质期统计',
                    subtext: '',
                    x: 'center'
                },
                tooltip: {
                    trigger: 'item',
                    formatter: "{a} <br/>{b} : {c}个 ({d}%)"
                },
                legend: {
                    orient: 'vertical',
                    left: 'left',
                    data: obj.data.legend
                },
                series: [
                    {
                        name: '保质期',
                        type: 'pie',
                        radius: '55%',
                        center: ['50%', '60%'],
                            data: obj.data.data,
                        itemStyle: {
                            emphasis: {
                                shadowBlur: 10,
                                shadowOffsetX: 0,
                                shadowColor: 'rgba(0, 0, 0, 0.5)'
                            }
                        }
                    }
                ]
            };
            var lineoption = option;
            lineChart.setOption(lineoption);
            $(window).resize(lineChart.resize);
        });
    })
</script>

{% endblock %}